import { createContext, useContext } from 'react';

/**
 * The admin app's language layer — the same pattern as apps/showcase/src/lang.tsx:
 * a `Lang` union, a context the whole tree reads, `useTr` for one-off pairs, and
 * a saved pick in localStorage. On top of that the panel keeps one typed
 * dictionary (`STRINGS`) with **every** key of **every** page, fa and en, so the
 * agents that fill the stub pages later only consume keys from here — they must
 * never need to edit this file.
 */

export type Lang = 'fa' | 'en';

export const LangContext = createContext<Lang>('fa');

export function useLang() {
  return useContext(LangContext);
}

/** `tr('ذخیره', 'Save')` — the panel speaks Persian first, English second. */
export function useTr() {
  const lang = useContext(LangContext);
  return (fa: string, en: string) => (lang === 'fa' ? fa : en);
}

/** Saved pick — localStorage first, safe default when storage is closed. */
export function readLang(): Lang {
  try {
    return localStorage.getItem('nabuxui.admin.lang') === 'en' ? 'en' : 'fa';
  } catch {
    return 'fa';
  }
}

/**
 * `'#1248'` → `'#۱۲۴۸'` in fa — seeded ids follow the panel language's digits,
 * the same roll the Livewire panel gets from `localeDigits` in ui-core (which
 * these ids cannot import: the panel depends only on @nabuxai/ui-react).
 */
export function localeId(value: string, lang: Lang): string {
  return lang === 'fa' ? value.replace(/[0-9]/g, (digit) => '۰۱۲۳۴۵۶۷۸۹'[Number(digit)]) : value;
}

/* ============================================================================
 * The dictionary. `fa` defines the shape; `en` fills the same shape.
 * ========================================================================== */

const fa = {
  app: {
    name: 'پنل نابو',
    brand: 'Nabu',
    tagline: 'مرکز کنترل فروشگاه شما',
    navLabel: 'ناوبری پنل',
    searchPlaceholder: 'جست‌وجو یا فرمان…',
    searchHint: '⌘K',
    notifications: 'اعلان‌ها',
    markAllRead: 'همه را خوانده‌شده کن',
    user: { name: 'حسین مرادی', role: 'مدیر سیستم', menuLabel: 'حساب کاربری' },
    login: 'ورود',
    logout: 'خروج',
    signedOut: 'از حساب خود خارج شدید',
    storeName: 'فروشگاه نابو',
  },
  nav: {
    main: 'مدیریت',
    work: 'فضای کار',
    account: 'حساب',
  },
  common: {
    search: 'جست‌وجو',
    save: 'ذخیره',
    saved: 'ذخیره شد',
    cancel: 'انصراف',
    delete: 'حذف',
    edit: 'ویرایش',
    close: 'بستن',
    add: 'افزودن',
    view: 'مشاهده',
    viewAll: 'دیدن همه',
    refresh: 'به‌روزرسانی',
    back: 'بازگشت',
    actions: 'عملیات',
    confirm: 'تأیید',
    selected: 'انتخاب‌شده',
    loading: 'در حال بارگذاری…',
    print: 'چاپ',
    export: 'خروجی',
    import: 'درون‌ریزی',
    today: 'امروز',
    yesterday: 'دیروز',
    online: 'آنلاین',
    away: 'غایب',
    busy: 'مشغول',
    offline: 'آفلاین',
    all: 'همه',
    yes: 'بله',
    no: 'خیر',
    more: 'بیشتر',
    comingSoon: 'به‌زودی',
    tzTehran: 'تهران (GMT+3:30)',
    tzBerlin: 'برلین (GMT+2:00)',
    currentPassword: 'رمز فعلی',
    newPassword: 'رمز تازه',
  },
  command: {
    pages: 'صفحه‌ها',
    actions: 'فرمان‌ها',
    goDashboard: 'رفتن به داشبورد',
    switchLang: 'تغییر زبان',
    signOut: 'خروج از حساب',
  },
  people: {
    maryam: 'مریم رضایی',
    ali: 'علی نیک‌پور',
    sara: 'سارا احمدی',
    mina: 'مینا کریمی',
  },
  pages: {
    dash: {
      title: 'داشبورد',
      subtitle: 'خلاصهٔ امروز فروشگاه شما',
      welcomeHi: 'خوش آمدید، حسین',
      welcomeText: 'امروز ۴۲ سفارش تازه، ۶ گفت‌وگوی باز و یک گزارش مالی آمادهٔ بررسی دارید.',
      welcomeCta: 'گزارش کامل',
      welcomeSecondary: 'دیدن کاربران',
      statsLabel: 'آمار امروز',
      statRevenue: 'فروش (تومان)',
      statRevenueCaption: '٪۱۲+ نسبت به دیروز',
      statOrders: 'سفارش‌ها',
      statOrdersCaption: '۴۲ سفارش تازه',
      statUsers: 'کاربران فعال',
      statUsersCaption: '٪۳+ این هفته',
      statSatisfaction: 'رضایت',
      statSatisfactionCaption: 'از ۱۰۰',
      metricTitle: 'سلامت فروشگاه',
      metricCaption: 'نسبت به دورهٔ قبل',
      metricRevenue: 'فروش',
      metricOrders: 'سفارش',
      metricVisits: 'بازدید',
      heatTitle: 'گفت‌وگوهای پاسخ‌داده‌شده',
      heatSubtitle: '۲۶ هفتهٔ اخیر · تیم پشتیبانی',
      heatUnit: 'گفت‌وگو',
      heatSummary: 'گفت‌وگو در شش ماه گذشته',
      feedTitle: 'جریان فعالیت',
      usageTitle: 'فضای ذخیره‌سازی',
      usagePlan: 'پرو',
      usageNote: 'اول هر ماه صفر می‌شود',
      usageAction: 'ارتقای طرح',
      usageDocs: 'اسناد',
      usageMedia: 'تصویر و ویدیو',
      usageVoice: 'پیام‌های صوتی',
      usageEmbeddings: 'بردارها',
    },
    analytics: {
      title: 'تحلیل‌ها',
      subtitle: 'روند فروش، بازدید و تبدیل در یک نگاه',
      emptyTitle: 'صفحهٔ تحلیل‌ها در راه است',
      emptyBody: 'نمودارها، جدول مقایسه و کارت‌های مصرف اینجا می‌نشینند.',
      action: 'بازگشت به داشبورد',
      secondary: 'دیدن کاربران',
      revenue: 'درآمد',
      orders: 'سفارش‌ها',
      visitors: 'بازدیدکننده',
      conversion: 'نرخ تبدیل',
      churn: 'ریزش',
      latency: 'زمان پاسخ',
      week: '۷ روز',
      month: '۳۰ روز',
      quarter: '۹۰ روز',
      vsPrev: 'نسبت به دورهٔ قبل',
      comparisonTitle: 'مقایسهٔ طرح‌ها',
      recommended: 'پیشنهاد ما',
      included: 'دارد',
      excluded: 'ندارد',
      monthly: '/ماه',
      cta: 'ارتقا',
      usageTitle: 'مصرف توکن مدل',
      usagePlan: 'رشد',
      usageNote: 'در ۱۰۰٪ ایجنت‌ها متوقف می‌شوند',
      usageAction: 'ارتقا',
      usageReplies: 'پاسخ‌ها',
      usageSummaries: 'خلاصه‌ها',
      usageTranslations: 'ترجمه‌ها',
      groupCapacity: 'ظرفیت',
      groupInsights: 'بینش',
      groupSupport: 'پشتیبانی',
      planBasic: 'پایه',
      planBasicDesc: 'برای شروع',
      planGrowth: 'رشد',
      planGrowthDesc: 'برای تیم‌های کوچک',
      planPro: 'حرفه‌ای',
      planProDesc: 'برای فروشگاههای بزرگ',
      featTeam: 'اعضای تیم',
      featUnlimited: 'نامحدود',
      featStorage: 'فضای ذخیره‌سازی',
      featGiftCards: 'کارت هدیه',
      featReports: 'گزارشهای تحلیلی',
      featExport: 'خروجی داده',
      featCompare: 'نمودارهای مقایسهٔ دوره',
      featEmail: 'پشتیبانی ایمیلی',
      featLiveChat: 'پشتیبانی زنده',
      featSuccessManager: 'مدیر موفقیت اختصاصی',
      percentSign: '٪',
      qualityTitle: 'کیفیت فروشگاه',
      featureLabel: 'ویژگی',
    },
    users: {
      title: 'کاربران',
      subtitle: 'مدیریت اعضا، نقش‌ها و دسترسی‌ها',
      emptyTitle: 'هنوز کاربری ساخته نشده',
      emptyBody: 'جدول کاربران با جست‌وجو، فیلتر و مرتب‌سازی اینجا می‌نشیند.',
      action: 'ساخت کاربر',
      secondary: 'دعوت با ایمیل',
      search: 'جست‌وجوی نام یا ایمیل…',
      filterAll: 'همه',
      active: 'فعال',
      inactive: 'غیرفعال',
      invited: 'دعوت‌شده',
      colName: 'نام',
      colEmail: 'ایمیل',
      colRole: 'نقش',
      colStatus: 'وضعیت',
      colLastSeen: 'آخرین فعالیت',
      roleAdmin: 'مدیر',
      roleManager: 'سرپرست',
      roleSupport: 'پشتیبانی',
      roleUser: 'کاربر',
      addUser: 'کاربر تازه',
      exportCsv: 'خروجی CSV',
      selectedCount: 'نفر انتخاب‌شده',
      deleteTitle: 'حذف کاربر',
      deleteBody: 'این کاربر برای همیشه حذف می‌شود. این عمل قابل بازگشت نیست.',
      selectAll: 'انتخاب همهٔ اعضا',
      select: 'انتخاب',
      removedSelected: 'کاربران انتخاب‌شده حذف شدند',
      csvReady: 'خروجی CSV آماده شد',
      noMatch: 'موردی مطابق فیلترها پیدا نشد',
      justNow: 'همین حالا',
    },
    kanban: {
      title: 'کانبان',
      subtitle: 'برد وظایف تیم، با کشیدن و رها کردن',
      emptyTitle: 'برد خالی است',
      emptyBody: 'ستون‌ها و کارت‌های برد وظایف اینجا می‌نشینند.',
      action: 'ساخت کارت',
      secondary: 'بازگشت به داشبورد',
      backlog: 'در انتظار',
      todo: 'انجام نشده',
      doing: 'در انجام',
      review: 'بازبینی',
      done: 'انجام شد',
      addCard: 'افزودن کارت',
      newCardPlaceholder: 'عنوان کارت تازه…',
      menuEdit: 'ویرایش',
      menuDelete: 'حذف',
      menuArchive: 'بایگانی',
      emptyColumn: 'کارتی نیست — اولین را بسازید',
    },
    calendar: {
      title: 'تقویم',
      subtitle: 'رویدادها و قرارهای ماه',
      emptyTitle: 'تقویم در راه است',
      emptyBody: 'گرید ماه و رویدادهای رنگی اینجا می‌نشینند.',
      action: 'رویداد تازه',
      secondary: 'امروز',
      today: 'امروز',
      upcoming: 'رویدادهای پیش‌رو',
      noEvents: 'رویدادی ثبت نشده',
      dayEvents: 'رویدادهای این روز',
      added: 'رویداد تازه ثبت شد',
      fieldTitle: 'عنوان',
      fieldDay: 'روز',
      fieldTime: 'ساعت',
    },
    chat: {
      title: 'گفت‌وگو',
      subtitle: 'پیام‌های تیم و مشتریان',
      emptyTitle: 'گفت‌وگی باز نیست',
      emptyBody: 'ستون گفت‌وگوها، رشتهٔ پیام‌ها و جعبهٔ نوشتن اینجا می‌نشینند.',
      action: 'گفت‌وگوی تازه',
      secondary: 'بازگشت به داشبورد',
      search: 'جست‌وجوی گفت‌وگو…',
      conversations: 'گفت‌وگوها',
      messages: 'پیام‌ها',
      placeholder: 'پیامتان را بنویسید…',
      send: 'ارسال',
      typing: 'در حال نوشتن…',
      noSelection: 'یک گفت‌وگو را انتخاب کنید',
      unread: 'خوانده‌نشده',
      acmeAccounts: 'حسابداری آدم',
      roleMaryam: 'مشتری · سفارش ۱۲۴۸',
      roleAli: 'تیم پشتیبانی',
      roleSara: 'مدیر محصول',
      roleAcme: 'حسابداری',
      roleCustomer: 'مشتری',
      maryamPreview: 'سلام! سفارشم کی به دستم می‌رسد؟',
      maryamM1: 'سلام! سفارش شمارهٔ ۱۲۴۸ را ثبت کردم.',
      maryamM2: 'بسته‌بندی هدیه هم امکان‌پذیر است؟',
      maryamM3: 'سلام مریم‌جان، بله! همراه با یک کارت تبریک می‌فرستیم.',
      maryamM4: 'عالی‌ست. کی به دستم می‌رسد؟',
      aliPreview: 'گزارش این هفته را می‌فرستم…',
      aliA1: 'علی، گزارش گفت‌وگوهای این هفته آماده است؟',
      aliA2: 'تقریباً؛ فقط نمودارها مانده.',
      saraPreview: 'جلسهٔ بازبینی ساعت ۱۶ لغو شد.',
      saraS1: 'یادآوری: بازبینی طراحی فردا ساعت ۱۰.',
      saraS2: 'هستم 👌',
      saraS3: 'جلسهٔ امروز ساعت ۱۶ لغو شد؛ فردا جبرانی می‌گیریم.',
      acmePreview: 'فاکتور INV-2026-118 پرداخت شد.',
      acmeAc1: 'فاکتور این ماه واریز شد.',
      acmeAc2: 'واریزی را دریافت کردیم، ممنون! رسید را فرستادیم.',
      minaPreview: 'کیف چرمی نابو عالی بود!',
      minaMi1: 'بسته رسید — کیف چرمی نابو واقعاً عالی بود!',
      minaMi2: 'خوشحالیم که پسندیدید 🌟',
      typingWith: '{name} در حال نوشتن…',
      noMessages: 'هنوز پیامی نیست؛ اولین را بنویسید.',
    },
    invoices: {
      title: 'فاکتورها',
      subtitle: 'اسناد مالی و وضعیت پرداخت',
      emptyTitle: 'فاکتوری نیست',
      emptyBody: 'سند فاکتور با اقلام، جمع‌ها و چاپ اینجا می‌نشیند.',
      action: 'فاکتور تازه',
      secondary: 'فاکتور نمونه',
      paid: 'پرداخت‌شده',
      unpaid: 'پرداخت‌نشده',
      overdue: 'معوق',
      draft: 'پیش‌نویس',
      from: 'صادرکننده',
      to: 'گیرنده',
      issueDate: 'تاریخ صدور',
      dueDate: 'سررسید',
      description: 'شرح',
      qty: 'تعداد',
      unitPrice: 'قیمت واحد',
      amount: 'مبلغ',
      subtotal: 'جمع کل',
      tax: 'مالیات',
      discount: 'تخفیف',
      total: 'مبلغ نهایی',
      print: 'چاپ فاکتور',
      tehran: 'تهران، ایران',
      isfahan: 'اصفهان، ایران',
      taxId: 'شناسه ملی ۱۴۰۰…',
      clientAcme: 'شرکت آدم',
      clientRangin: 'گالری رنگین',
      clientInternal: 'داخلی · بازبینی طراحی',
      itemBag: 'کیف چرمی نابو',
      itemBagDesc: 'چرم طبیعی، دوخت دست',
      itemScarf: 'شال کشمیر نابو',
      itemScarfDesc: 'سه رنگ قابل انتخاب',
      itemWrap: 'بسته‌بندی هدیه',
      itemWrapDesc: 'همراه با کارت تبریک',
      itemWatch: 'ساعت نابو کلاسیک',
      itemWatchDesc: 'بدنهٔ استیل، بند چرمی',
      itemSupport: 'پشتیبانی ماهانه',
      itemSupportDesc: 'دو روز اختصاصی در ماه',
      itemPrint: 'چاپ محدود پوستر',
      itemPrintDesc: 'سری ده‌تایی، امضاشده',
      itemShip: 'ارسال بیمه‌شده',
      itemAudit: 'بازبینی دسترس‌پذیری',
      itemRtl: 'پیمایش راست‌به‌چپ',
      lateFeeNote: 'پرداخت تا موعد اعلام‌شده؛ پس از آن دیرکرد ۲٪ در ماه حساب می‌شود.',
      currency: 'تومان',
      footer: 'فروشگاه نابو · billing@nabu.shop · سپاس از خرید شما.',
      docTitle: 'فاکتور',
      numberLabel: 'شمارهٔ فاکتور',
      paymentCaption: 'کارت به کارت · بانک نابو · شماره کارت ۶۱۰۴…',
    },
    profile: {
      title: 'پروفایل',
      subtitle: 'اطلاعات حساب و امنیت',
      emptyTitle: 'پروفایل در راه است',
      emptyBody: 'اطلاعات شخصی، جلسات و امنیت اینجا می‌نشینند.',
      action: 'ویرایش پروفایل',
      secondary: 'بازگشت به داشبورد',
      personal: 'اطلاعات شخصی',
      security: 'امنیت',
      sessions: 'دستگاههای فعال',
      name: 'نام و نام خانوادگی',
      email: 'ایمیل',
      role: 'نقش',
      bio: 'دربارهٔ من',
      timezone: 'منطقهٔ زمانی',
      phone: 'شمارهٔ تماس',
      changeAvatar: 'تغییر تصویر',
      lastActive: 'آخرین فعالیت',
      revoke: 'خروج از دستگاه',
      deviceMac: 'کروم · مک‌اواس',
      deviceIphone: 'سافاری · آیفون',
      whenIphone: '۱۸ دقیقه پیش',
      deviceWindows: 'فایرفاکس · ویندوز',
      whenWindows: 'دو روز پیش',
      avatarHint: 'PNG یا JPG، حداکثر ۲ مگابایت',
      bioDefault: 'مدیر سیستم فروشگاه نابو؛ علاقه‌مند به ابزارهای خوب و تنظیمات ریز.',
      newPasswordHint: 'حداقل ۸ نویسه، با عدد و نویسهٔ بزرگ',
      updatePassword: 'به‌روزرسانی رمز',
      thisDevice: 'این دستگاه',
      currentDeviceHint: 'برای دستگاه فعلی، از تنظیمات خارج شوید',
    },
    settings: {
      title: 'تنظیمات',
      subtitle: 'پیکربندی فروشگاه و ترجیحات شما',
      emptyTitle: 'تنظیمات در راه است',
      emptyBody: 'فرم‌های عمومی، ظاهر، زبان و منطقهٔ خطر اینجا می‌نشینند.',
      action: 'شروع تنظیمات',
      secondary: 'بازگشت به داشبورد',
      general: 'عمومی',
      appearance: 'ظاهر',
      languageSection: 'زبان',
      notifications: 'اعلان‌ها',
      security: 'امنیت',
      danger: 'منطقهٔ خطر',
      workspaceName: 'نام فروشگاه',
      workspaceUrl: 'نشانی فروشگاه',
      timezoneField: 'منطقهٔ زمانی',
      theme: 'پوسته',
      themeLight: 'روشن',
      themeSystem: 'سیستم',
      themeDark: 'تیره',
      languageFa: 'فارسی',
      languageEn: 'English',
      emailDigest: 'خلاصهٔ روزانهٔ ایمیل',
      pushAlerts: 'اعلانهای فوری',
      weeklyReport: 'گزارش هفتگی',
      twoFactor: 'ورود دومرحله‌ای',
      password: 'تغییر رمز عبور',
      signOutDevices: 'خروج از همهٔ دستگاهها',
      deleteWorkspace: 'حذف فروشگاه',
      deleteBody: 'همهٔ داده‌ها برای همیشه حذف می‌شوند. این عمل قابل بازگشت نیست.',
      typeToDelete: 'برای تأیید، «حذف» را بنویسید',
      deleteWord: 'حذف',
      signedOutEverywhere: 'از همهٔ دستگاه‌ها خارج شدید',
      storeDeleted: 'فروشگاه حذف شد',
      themeHint: 'روشن، تیره یا دنبالِ سیستم — بلافاصله اعمال می‌شود.',
      languageHint: 'پس از انتخاب، پنل با زبان تازه بارگذاری می‌شود.',
      passwordDescription: 'یک رمز تازه با حداقل ۸ نویسه انتخاب کنید.',
      passwordUpdated: 'رمز عبور به‌روزرسانی شد',
      confirmWord: 'واژهٔ تأیید',
    },
    auth: {
      loginTitle: 'ورود',
      registerTitle: 'ثبت‌نام',
      forgotTitle: 'بازیابی رمز',
      stubTitle: 'نمای ورود در راه است',
      stubBody: 'کارت ورود با فرم‌های ورود، ثبت‌نام و بازیابی رمز اینجا می‌نشیند.',
      backToPanel: 'بازگشت به پنل',
      backToLogin: 'بازگشت به ورود',
      noAccount: 'حساب ندارید؟ ثبت‌نام',
      hasAccount: 'حساب دارید؟ ورود',
      resetSent: 'پیوند بازنشانی به ایمیلتان فرستاده شد.',
      welcomeBack: 'خوش آمدید!',
      accountReady: 'حسابتان آماده شد — خوش آمدید!',
      perkOrders: 'سفارش‌ها و گفت‌وگوها در یک صفحه',
      perkReports: 'گزارش‌های زندهٔ فروش',
      perkBilingual: 'دوزبانه و راست‌به‌چپ، روشن و تیره',
    },
  },
};

export type Strings = typeof fa;

const en: Strings = {
  app: {
    name: 'Nabu Panel',
    brand: 'Nabu',
    tagline: 'Your store’s control room',
    navLabel: 'Panel navigation',
    searchPlaceholder: 'Search or run a command…',
    searchHint: '⌘K',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    user: { name: 'Hossein Moradi', role: 'System admin', menuLabel: 'Account' },
    login: 'Sign in',
    logout: 'Sign out',
    signedOut: 'You have signed out',
    storeName: 'Nabu Store',
  },
  nav: {
    main: 'Manage',
    work: 'Workspace',
    account: 'Account',
  },
  common: {
    search: 'Search',
    save: 'Save',
    saved: 'Saved',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    add: 'Add',
    view: 'View',
    viewAll: 'View all',
    refresh: 'Refresh',
    back: 'Back',
    actions: 'Actions',
    confirm: 'Confirm',
    selected: 'selected',
    loading: 'Loading…',
    print: 'Print',
    export: 'Export',
    import: 'Import',
    today: 'Today',
    yesterday: 'Yesterday',
    online: 'Online',
    away: 'Away',
    busy: 'Busy',
    offline: 'Offline',
    all: 'All',
    yes: 'Yes',
    no: 'No',
    more: 'More',
    comingSoon: 'Coming soon',
    tzTehran: 'Tehran (GMT+3:30)',
    tzBerlin: 'Berlin (GMT+2:00)',
    currentPassword: 'Current password',
    newPassword: 'New password',
  },
  command: {
    pages: 'Pages',
    actions: 'Commands',
    goDashboard: 'Go to dashboard',
    switchLang: 'Switch language',
    signOut: 'Sign out',
  },
  people: {
    maryam: 'Maryam Rezaei',
    ali: 'Ali Nikpour',
    sara: 'Sara Ahmadi',
    mina: 'Mina Karimi',
  },
  pages: {
    dash: {
      title: 'Dashboard',
      subtitle: 'Your store, today at a glance',
      welcomeHi: 'Welcome back, Hossein',
      welcomeText: 'Today you have 42 new orders, 6 open conversations and one financial report ready to review.',
      welcomeCta: 'Full report',
      welcomeSecondary: 'See users',
      statsLabel: 'Today’s numbers',
      statRevenue: 'Revenue (USD)',
      statRevenueCaption: '+12% vs yesterday',
      statOrders: 'Orders',
      statOrdersCaption: '42 new orders',
      statUsers: 'Active users',
      statUsersCaption: '+3% this week',
      statSatisfaction: 'Satisfaction',
      statSatisfactionCaption: 'out of 100',
      metricTitle: 'Store health',
      metricCaption: 'vs previous period',
      metricRevenue: 'Revenue',
      metricOrders: 'Orders',
      metricVisits: 'Visits',
      heatTitle: 'Conversations answered',
      heatSubtitle: 'Last 26 weeks · support team',
      heatUnit: 'conversations',
      heatSummary: 'conversations in the last six months',
      feedTitle: 'Activity feed',
      usageTitle: 'Storage',
      usagePlan: 'Pro',
      usageNote: 'Resets on the 1st',
      usageAction: 'Upgrade plan',
      usageDocs: 'Documents',
      usageMedia: 'Images & video',
      usageVoice: 'Voice notes',
      usageEmbeddings: 'Embeddings',
    },
    analytics: {
      title: 'Analytics',
      subtitle: 'Revenue, visits and conversion in one view',
      emptyTitle: 'Analytics is on its way',
      emptyBody: 'Charts, the plan comparison and usage cards land here.',
      action: 'Back to dashboard',
      secondary: 'See users',
      revenue: 'Revenue',
      orders: 'Orders',
      visitors: 'Visitors',
      conversion: 'Conversion',
      churn: 'Churn',
      latency: 'Latency',
      week: '7 days',
      month: '30 days',
      quarter: '90 days',
      vsPrev: 'vs previous period',
      comparisonTitle: 'Compare plans',
      recommended: 'Our pick',
      included: 'Included',
      excluded: 'Not included',
      monthly: '/mo',
      cta: 'Upgrade',
      usageTitle: 'Model tokens',
      usagePlan: 'Growth',
      usageNote: 'Agents pause at 100%',
      usageAction: 'Upgrade',
      usageReplies: 'Replies',
      usageSummaries: 'Summaries',
      usageTranslations: 'Translations',
      groupCapacity: 'Capacity',
      groupInsights: 'Insights',
      groupSupport: 'Support',
      planBasic: 'Basic',
      planBasicDesc: 'To get going',
      planGrowth: 'Growth',
      planGrowthDesc: 'For small teams',
      planPro: 'Pro',
      planProDesc: 'For large stores',
      featTeam: 'Team members',
      featUnlimited: 'Unlimited',
      featStorage: 'Storage',
      featGiftCards: 'Gift cards',
      featReports: 'Analytics reports',
      featExport: 'Data export',
      featCompare: 'Period comparison charts',
      featEmail: 'Email support',
      featLiveChat: 'Live chat support',
      featSuccessManager: 'Dedicated success manager',
      percentSign: '%',
      qualityTitle: 'Store quality',
      featureLabel: 'Feature',
    },
    users: {
      title: 'Users',
      subtitle: 'Members, roles and access',
      emptyTitle: 'No users yet',
      emptyBody: 'The users table — search, filters, sorting — lands here.',
      action: 'Create user',
      secondary: 'Invite by email',
      search: 'Search name or email…',
      filterAll: 'All',
      active: 'Active',
      inactive: 'Inactive',
      invited: 'Invited',
      colName: 'Name',
      colEmail: 'Email',
      colRole: 'Role',
      colStatus: 'Status',
      colLastSeen: 'Last seen',
      roleAdmin: 'Admin',
      roleManager: 'Manager',
      roleSupport: 'Support',
      roleUser: 'User',
      addUser: 'New user',
      exportCsv: 'Export CSV',
      selectedCount: 'selected',
      deleteTitle: 'Delete user',
      deleteBody: 'This user is removed forever. This cannot be undone.',
      selectAll: 'Select every member',
      select: 'Select',
      removedSelected: 'The selected users were removed',
      csvReady: 'The CSV export is ready',
      noMatch: 'No one matches these filters',
      justNow: 'just now',
    },
    kanban: {
      title: 'Kanban',
      subtitle: 'The team board, with drag and drop',
      emptyTitle: 'The board is empty',
      emptyBody: 'Columns and task cards land here.',
      action: 'Create card',
      secondary: 'Back to dashboard',
      backlog: 'Backlog',
      todo: 'To do',
      doing: 'In progress',
      review: 'Review',
      done: 'Done',
      addCard: 'Add a card',
      newCardPlaceholder: 'New card title…',
      menuEdit: 'Edit',
      menuDelete: 'Delete',
      menuArchive: 'Archive',
      emptyColumn: 'No cards — add the first one',
    },
    calendar: {
      title: 'Calendar',
      subtitle: 'The month’s events and meetings',
      emptyTitle: 'Calendar is on its way',
      emptyBody: 'The month grid and colour-coded events land here.',
      action: 'New event',
      secondary: 'Today',
      today: 'Today',
      upcoming: 'Upcoming',
      noEvents: 'No events yet',
      dayEvents: 'Events on this day',
      added: 'The new event was added',
      fieldTitle: 'Title',
      fieldDay: 'Day',
      fieldTime: 'Time',
    },
    chat: {
      title: 'Chat',
      subtitle: 'Team and customer conversations',
      emptyTitle: 'No conversation open',
      emptyBody: 'The conversation list, thread and composer land here.',
      action: 'New conversation',
      secondary: 'Back to dashboard',
      search: 'Search conversations…',
      conversations: 'Conversations',
      messages: 'Messages',
      placeholder: 'Write your message…',
      send: 'Send',
      typing: 'typing…',
      noSelection: 'Pick a conversation',
      unread: 'unread',
      acmeAccounts: 'Acme accounts',
      roleMaryam: 'Customer · order #1248',
      roleAli: 'Support team',
      roleSara: 'Product manager',
      roleAcme: 'Accounts',
      roleCustomer: 'Customer',
      maryamPreview: 'Hi! When will my order arrive?',
      maryamM1: 'Hi! I placed order #1248.',
      maryamM2: 'Is gift wrapping possible?',
      maryamM3: 'Hi Maryam, yes! We will include a greeting card.',
      maryamM4: 'Perfect. When will it arrive?',
      aliPreview: 'Sending this week’s report…',
      aliA1: 'Ali, is this week’s conversation report ready?',
      aliA2: 'Almost; only the charts are left.',
      saraPreview: 'The 4 o’clock review is cancelled.',
      saraS1: 'Reminder: the design review tomorrow at 10.',
      saraS2: 'I’ll be there 👌',
      saraS3: 'Today’s 4 o’clock meeting is cancelled; we will make up for it tomorrow.',
      acmePreview: 'Invoice INV-2026-118 was paid.',
      acmeAc1: 'This month’s invoice was transferred.',
      acmeAc2: 'We received the transfer, thank you! The receipt is on its way.',
      minaPreview: 'The Nabu leather bag was perfect!',
      minaMi1: 'The parcel arrived — the Nabu leather bag is really perfect!',
      minaMi2: 'So glad you love it 🌟',
      typingWith: '{name} is typing…',
      noMessages: 'No messages yet; write the first one.',
    },
    invoices: {
      title: 'Invoices',
      subtitle: 'Financial documents and payment status',
      emptyTitle: 'No invoices',
      emptyBody: 'The invoice document — lines, totals, printing — lands here.',
      action: 'New invoice',
      secondary: 'Sample invoice',
      paid: 'Paid',
      unpaid: 'Unpaid',
      overdue: 'Overdue',
      draft: 'Draft',
      from: 'From',
      to: 'Bill to',
      issueDate: 'Issue date',
      dueDate: 'Due date',
      description: 'Description',
      qty: 'Qty',
      unitPrice: 'Unit price',
      amount: 'Amount',
      subtotal: 'Subtotal',
      tax: 'Tax',
      discount: 'Discount',
      total: 'Total',
      print: 'Print invoice',
      tehran: 'Tehran, Iran',
      isfahan: 'Isfahan, Iran',
      taxId: 'Tax id 1400…',
      clientAcme: 'Acme Corp',
      clientRangin: 'Rangin Gallery',
      clientInternal: 'Internal · design review',
      itemBag: 'Nabu leather bag',
      itemBagDesc: 'Full-grain leather, hand stitched',
      itemScarf: 'Nabu cashmere scarf',
      itemScarfDesc: 'Three colourways',
      itemWrap: 'Gift wrapping',
      itemWrapDesc: 'With a greeting card',
      itemWatch: 'Nabu classic watch',
      itemWatchDesc: 'Steel case, leather strap',
      itemSupport: 'Monthly support',
      itemSupportDesc: 'Two dedicated days a month',
      itemPrint: 'Limited poster print',
      itemPrintDesc: 'Signed run of ten',
      itemShip: 'Insured shipping',
      itemAudit: 'Accessibility audit',
      itemRtl: 'RTL sweep',
      lateFeeNote: 'Payable by the due date; afterwards a late fee of 2% per month applies.',
      currency: 'Toman',
      footer: 'Nabu Store · billing@nabu.shop · Thank you for your purchase.',
      docTitle: 'Invoice',
      numberLabel: 'Invoice no.',
      paymentCaption: 'Bank transfer · Nabu Bank · card 6104…',
    },
    profile: {
      title: 'Profile',
      subtitle: 'Account details and security',
      emptyTitle: 'Profile is on its way',
      emptyBody: 'Personal details, sessions and security land here.',
      action: 'Edit profile',
      secondary: 'Back to dashboard',
      personal: 'Personal details',
      security: 'Security',
      sessions: 'Active devices',
      name: 'Full name',
      email: 'Email',
      role: 'Role',
      bio: 'About me',
      timezone: 'Time zone',
      phone: 'Phone',
      changeAvatar: 'Change photo',
      lastActive: 'Last active',
      revoke: 'Sign out device',
      deviceMac: 'Chrome · macOS',
      deviceIphone: 'Safari · iPhone',
      whenIphone: '18 minutes ago',
      deviceWindows: 'Firefox · Windows',
      whenWindows: 'two days ago',
      avatarHint: 'PNG or JPG, up to 2 MB',
      bioDefault: 'Nabu Store’s system admin; fond of good tooling and careful tuning.',
      newPasswordHint: 'At least 8 characters, with a digit and an uppercase',
      updatePassword: 'Update password',
      thisDevice: 'This device',
      currentDeviceHint: 'For the current device, sign out from settings',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Store configuration and your preferences',
      emptyTitle: 'Settings is on its way',
      emptyBody: 'General, appearance, language and the danger zone land here.',
      action: 'Start settings',
      secondary: 'Back to dashboard',
      general: 'General',
      appearance: 'Appearance',
      languageSection: 'Language',
      notifications: 'Notifications',
      security: 'Security',
      danger: 'Danger zone',
      workspaceName: 'Store name',
      workspaceUrl: 'Store URL',
      timezoneField: 'Time zone',
      theme: 'Theme',
      themeLight: 'Light',
      themeSystem: 'System',
      themeDark: 'Dark',
      languageFa: 'فارسی',
      languageEn: 'English',
      emailDigest: 'Daily email digest',
      pushAlerts: 'Push alerts',
      weeklyReport: 'Weekly report',
      twoFactor: 'Two-factor sign-in',
      password: 'Change password',
      signOutDevices: 'Sign out everywhere',
      deleteWorkspace: 'Delete store',
      deleteBody: 'All data is removed forever. This cannot be undone.',
      typeToDelete: 'Type “delete” to confirm',
      deleteWord: 'delete',
      signedOutEverywhere: 'Signed out on all devices',
      storeDeleted: 'The store was deleted',
      themeHint: 'Light, dark or follow the system — applied right away.',
      languageHint: 'Picking one reloads the panel in the new language.',
      passwordDescription: 'Pick a new password of at least 8 characters.',
      passwordUpdated: 'Password updated',
      confirmWord: 'Confirmation word',
    },
    auth: {
      loginTitle: 'Sign in',
      registerTitle: 'Create account',
      forgotTitle: 'Reset password',
      stubTitle: 'The sign-in view is on its way',
      stubBody: 'The auth card — sign in, register, reset — lands here.',
      backToPanel: 'Back to the panel',
      backToLogin: 'Back to sign in',
      noAccount: 'No account? Register',
      hasAccount: 'Have an account? Sign in',
      resetSent: 'A reset link is on its way to your email.',
      welcomeBack: 'Welcome back!',
      accountReady: 'Your account is ready — welcome!',
      perkOrders: 'Orders and conversations on one screen',
      perkReports: 'Live sales reports',
      perkBilingual: 'Bilingual, RTL-native, light and dark',
    },
  },
};

export const STRINGS: Record<Lang, Strings> = { fa, en };

/** The whole dictionary for the current language — `s.pages.users.title`. */
export function useStrings(): Strings {
  return STRINGS[useLang()];
}
